In [276]:
#imports

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.utils import plot_model
import random
import numpy

In [277]:
#definitions

DIMENSIONS=2
SENSORS=[[0.2,0.3],[0.2,0.4],[0.5,0.3],[0.4,0.3]]

INPUT_NODES = len(SENSORS)
HIDDEN_NODES = [64,64]
OUTPUT_NODES = DIMENSIONS



In [278]:
#Generate train data
input_data = []
xOutput_data = []
yOutput_data = []
for i in range (10000):
    x = random.random()
    y = random.random()
    xOutput_data.append(numpy.array(x))
    yOutput_data.append(numpy.array(y))
    input_data.append(numpy.array([
        ((x-SENSORS[0][0])**2 + (y-SENSORS[0][1])**2)**0.5,
        ((x-SENSORS[1][0])**2 + (y-SENSORS[1][1])**2)**0.5,
        ((x-SENSORS[2][0])**2 + (y-SENSORS[2][1])**2)**0.5,
        ((x-SENSORS[3][0])**2 + (y-SENSORS[3][1])**2)**0.5,
    ]))
input_data = numpy.array(input_data)
output_data = numpy.array(output_data)

In [279]:
#Generate Model

inp = Input((INPUT_NODES,))

#model = keras.Sequential()
#model.add(Dense(INPUT_NODES))
x = Dense(128, activation='relu')(inp)
x = Dense(128, activation='relu')(x)
x = Dense(128, activation='relu')(x)
x = Dense(128, activation='relu')(x)
#for nodes in HIDDEN_NODES:
    #x = Dense(nodes, activation='relu')(x)
    #model.add(Dense(nodes,activation=tf.nn.relu))
xOut = Dense(1, activation='sigmoid', name='xOut')(x)
yOut = Dense(1, activation='sigmoid', name='yOut')(x)
model = Model(inputs=inp, outputs=[xOut, yOut])
#model.add(Dense(OUTPUT_NODES))
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])


In [280]:
model.fit(input_data,[xOutput_data, yOutput_data,],epochs =50)

Epoch 1/50
10000/10000 [==============================] - 7s 673us/step - loss: 0.0223 - xOut_loss: 0.0076 - yOut_loss: 0.0148 - xOut_acc: 0.0000e+00 - yOut_acc: 0.0000e+00
Epoch 2/50
10000/10000 [==============================] - 3s 259us/step - loss: 0.0012 - xOut_loss: 4.3037e-04 - yOut_loss: 8.0140e-04 - xOut_acc: 0.0000e+00 - yOut_acc: 0.0000e+00
Epoch 3/50
10000/10000 [==============================] - 3s 251us/step - loss: 5.1540e-04 - xOut_loss: 1.8604e-04 - yOut_loss: 3.2937e-04 - xOut_acc: 0.0000e+00 - yOut_acc: 0.0000e+00
Epoch 4/50
10000/10000 [==============================] - 3s 255us/step - loss: 5.2558e-04 - xOut_loss: 1.4076e-04 - yOut_loss: 3.8483e-04 - xOut_acc: 0.0000e+00 - yOut_acc: 0.0000e+00
Epoch 5/50
10000/10000 [==============================] - 3s 252us/step - loss: 3.0860e-04 - xOut_loss: 9.5225e-05 - yOut_loss: 2.1338e-04 - xOut_acc: 0.0000e+00 - yOut_acc: 0.0000e+00
Epoch 6/50
10000/10000 [==============================] - 3s 256us/step - loss: 3.5651e-04 

10000/10000 [==============================] - 3s 262us/step - loss: 7.9497e-05 - xOut_loss: 1.7523e-05 - yOut_loss: 6.1974e-05 - xOut_acc: 0.0000e+00 - yOut_acc: 0.0000e+00
Epoch 46/50
10000/10000 [==============================] - 3s 264us/step - loss: 8.4755e-05 - xOut_loss: 3.2386e-05 - yOut_loss: 5.2369e-05 - xOut_acc: 0.0000e+00 - yOut_acc: 0.0000e+00
Epoch 47/50
10000/10000 [==============================] - 3s 279us/step - loss: 9.3000e-05 - xOut_loss: 2.2815e-05 - yOut_loss: 7.0184e-05 - xOut_acc: 0.0000e+00 - yOut_acc: 0.0000e+00
Epoch 48/50
10000/10000 [==============================] - 3s 262us/step - loss: 3.2488e-05 - xOut_loss: 1.1079e-05 - yOut_loss: 2.1409e-05 - xOut_acc: 0.0000e+00 - yOut_acc: 0.0000e+00
Epoch 49/50
10000/10000 [==============================] - 3s 270us/step - loss: 2.2395e-04 - xOut_loss: 4.7661e-05 - yOut_loss: 1.7629e-04 - xOut_acc: 0.0000e+00 - yOut_acc: 0.0000e+00
Epoch 50/50
10000/10000 [==============================] - 3s 261us/step - loss: 1

In [284]:
#result = model.predict(input_data)

x = 0.23454325
y = 0.54214774

test = numpy.array([[
        ((x-SENSORS[0][0])**2 + (y-SENSORS[0][1])**2)**0.5,
        ((x-SENSORS[1][0])**2 + (y-SENSORS[1][1])**2)**0.5,
        ((x-SENSORS[2][0])**2 + (y-SENSORS[2][1])**2)**0.5,
        ((x-SENSORS[3][0])**2 + (y-SENSORS[3][1])**2)**0.5,
    ]])

print(type(input_data))

result = model.predict(test)

print(input_data)

#for i in range(500):
#    print(result[0][i], "\t", result[1][i], "\t\t", xOutput_data[i], "\t", yOutput_data[i])

<class 'numpy.ndarray'>
[[0.47884171 0.5328091  0.2550214  0.31589092]
 [0.47721849 0.38539423 0.64771109 0.57930901]
 [0.75956301 0.8035479  0.4966517  0.58030503]
 ...
 [0.17620968 0.07909339 0.37128334 0.28679405]
 [0.84402637 0.77738868 0.66361547 0.71487796]
 [0.77620775 0.80942702 0.49468669 0.58649476]]
